[GITHUB ACTION AUTOMATING] new feature like check the compilation, check the repo and check the test

diff --git a/.github/worflows/check_program.yml b/.github/worflows/check_program.yml
--- a/.github/worflows/check_program.yml
+++ b/.github/worflows/check_program.yml
@@ -5,11 +5,62 @@ on :
     branches :
       - main
 
+env:
+  MIRROR_URL: "put the mirror url here (the ssh github of your repo) or leave it empty"
+  EXECUTABLES: " put the name of the executable here (ex: ./my_executable) or leave it empty"
+
 jobs:
-  coding_style:
+  check_coding_style:
     name: Coding Style
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: check coding style
         run: curl -fsSL https://raw.githubusercontent.com/estebanbaigts/Github-action-for-epitech/main/coding-style.sh | bash -s . .
+  check_repo:
+    name: "Checks if the repo is clean"
+    runs-on: ubuntu-latest
+    needs : [check_coding_style]
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_repo
+        run: |
+          if [[ $(git status --porcelain) ]]
+          then
+            echo "::error file=README.md,title=Repo is not clean::"
+            exit 1
+          else
+            echo Repo is clean
+          fi
+  check_program_compilation:
+    needs: [check_coding_style, check_repo]
+    name: "Checks if the program compiles"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_program_compilation
+        run: make
+        timeout-minutes: 2
+      - run: make clean
+      - run: |
+          OIFS=$IFS
+          IFS=','
+          for x in $EXECUTABLES
+            do
+              ./$x $ARGUMENTS
+            done
+          IFS=$OIFS
+  
+  run_tests:
+    needs: [check_coding_style, check_repo, check_program_compilation]
+    name: "Runs the tests"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@v3
+      - id: run_tests
+        run: make tests_run
+        timeout-minutes: 2
